name: On Push

on: push

jobs:
  build-test-deploy:
    name: Build, Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Calculate Build Target
        if: ${{ contains(github.refs, github.repository.default_branch) }}
        run: echo "BUILD_TARGET=deploy" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: Build & Test & Deploy
        uses: docker/build-push-action@v2.7.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          target: release
